### ISSUE TITLE
Build failed with gcc and clang.

### ISSUE THREAD

**Issue by aster2013** [satoren/kaguya#43]
gcc
https://travis-ci.org/urho3d/Urho3D/jobs/149706862

Clang:
https://travis-ci.org/urho3d/Urho3D/jobs/149706864

**Comment by aster2013** [comment]
Which version of boost you used?

**Comment by satoren** [comment]
I used 1.46(travis-ci), 1.56(appveyor) , 1.58(Ubuntu and cygwin), 1.60(Windows)
Maybe not enough on https://github.com/urho3d/Urho3D/tree/new-lua-script-test/Source/ThirdParty/boost

**Comment by satoren** [comment]
I tried build on Ubuntu 12.04 with g++4.6.  I encounter error too.

Error at `kaguya/push_tuple.hpp:20:10: error: expected nested-name-specifier before ‘type’`
but this line is in `#if KAGUYA_USE_CPP11`
g++4.6 is not supported C++11. Strange it. :sweat:

**Comment by aster2013** [comment]
More arguments support in kaguya, current is 10, but I need 25.

**Comment by satoren** [comment]
Realy? What to use it?

**Comment by satoren** [comment]
added KAGUYA_FUNCTION_MAX_ARGS for more arguments support.
but overload function number is limited by  boost::tuple. boost::tuple size is up to 10.

equal can not this.
```
    lua["Variant"].setClass(UserdataMetatable<Variant>()
        .setConstructors<Variant(),
        Variant(int),
        Variant(const StringHash&),
        Variant(bool),
        Variant(double),
        Variant(const Vector2&),
        Variant(const Vector3&),
        Variant(const Vector4&),
        Variant(const Quaternion&),
        Variant(const Color&),
        Variant(const char*),
        Variant(const ResourceRef&),
        Variant(const ResourceRefList&),
        Variant(const VariantVector&),
        Variant(const VariantMap&),
        Variant(const StringVector&),
        Variant(const IntRect&),
        Variant(const IntVector2&),
        Variant(RefCounted*),
        Variant(const Matrix3&),
        Variant(const Matrix3x4&),
        Variant(const Matrix4&)> ()
```

**Comment by aster2013** [comment]
Thanks, but how to solve it?

**Comment by aster2013** [comment]
Please take a look here:

http://stackoverflow.com/questions/6425178/boost-tuple-increasing-maximum-number-of-elements

**Comment by aster2013** [comment]
with boost::fusion I can build it on MinGW and Ubuntu.

**Comment by satoren** [comment]
Added tuple by self implementation for overloads.

**Comment by aster2013** [comment]
Thanks, I will check it later.

**Comment by aster2013** [comment]
the new tuple self implementation will remain failed. please use boost::fusion::tuple.

**Comment by satoren** [comment]
Did you changed only KAGUYA_FUNCTION_MAX_OVERLOADS?

KAGUYA_FUNCTION_MAX_TUPLE_SIZE does not  affect the overloads,
and it can not over the 10 because it dependent on the boost::tuple.

**Comment by aster2013** [comment]
Yes, I use following define:
```
#define KAGUYA_FUNCTION_MAX_ARGS 12
#define KAGUYA_FUNCTION_MAX_TUPLE_SIZE 24
#define KAGUYA_FUNCTION_MAX_OVERLOADS 9
```
but these is some bug in kaguya. 
for example:

KAGUYA_PP_REPEAT_DEF(**KAGUYA_FUNCTION_MAX_TUPLE_SIZE**, KAGUYA_MULTIPLE_INHERITANCE_SETBASE_DEF)

**Comment by aster2013** [comment]
You can check out Urho3D new-lua-script-test branch. It can build success with boost::fusion::tuple. 
and then you can switch it to your implementation tuple for testing.
Thanks.

**Comment by satoren** [comment]
KAGUYA_MULTIPLE_INHERITANCE_SETBASE_DEF is inheritance class implement. it is not affect overloads.

**Comment by satoren** [comment]
build pass at MSVC 2015 with boost
and this options.
```
#define KAGUYA_USE_CPP11 0
#define KAGUYA_FUNCTION_MAX_ARGS 25
#define KAGUYA_FUNCTION_MAX_TUPLE_SIZE 9
#define KAGUYA_FUNCTION_MAX_OVERLOADS 25
```

**Comment by satoren** [comment]
This is another bug but.

In clang++ , libstdc++ , -std=c++11 
std::tuple is  limited to 16. :scream:

http://stackoverflow.com/questions/23374953/why-does-this-exceed-the-maximum-recursive-template-depth

**Comment by aster2013** [comment]
Hi, these is another compiler error, pls. take a look.
https://travis-ci.org/urho3d/Urho3D/jobs/151133270

**Comment by aster2013** [comment]
with boost build time is too long up to 40 minutes.

**Comment by satoren** [comment]
If KAGUYA_FUNCTION_MAX_OVERLOADS is defined, uses self tuple implementation including on C++11,
since 6ea947a08330c1003fcc772489726fa5b90afb94


> with boost build time is too long up to 40 minutes.

What environment? My environment is no difference.
https://travis-ci.org/satoren/kaguya/builds/151080943
